#!/usr/bin/env python3
"""Export holosoma_inference presets to the YAML files read by holosoma_cpp.

The C++ runtime has no Python dependency, so it reads the inference presets
from ``config/inference/<name>.yaml``. These files are generated from the
Python ``INFERENCE_REGISTRY`` so both runtimes start from identical values.

Usage:
    python export_presets.py            # rewrite the YAML files
    python export_presets.py --check    # fail if a YAML file is out of date
"""

from __future__ import annotations

import argparse
import dataclasses
import difflib
import os
import sys
from pathlib import Path

import yaml

PACKAGE_DIR = Path(__file__).resolve().parents[1]
PRESET_DIR = PACKAGE_DIR / "config" / "inference"
REPO_ROOT = PACKAGE_DIR.parents[1]

# Presets the C++ runtime supports. T1 uses the Booster SDK, which has no C++ backend yet.
EXPORTED_PRESETS = ("g1-29dof-loco", "g1-29dof-wbt")

HEADER = (
    "# Generated by src/holosoma_inference/holosoma_cpp/scripts/export_presets.py from the\n"
    "# holosoma_inference preset '{name}'. Do not edit by hand; re-run the script.\n"
    "# Relative model paths are resolved against this file's directory.\n"
)


class _Dumper(yaml.SafeDumper):
    """Block-style mappings with flow-style scalar lists."""


def _represent_list(dumper: yaml.SafeDumper, data: list):
    flow = all(not isinstance(item, (dict, list)) for item in data)
    return dumper.represent_sequence("tag:yaml.org,2002:seq", data, flow_style=flow)


_Dumper.add_representer(list, _represent_list)
_Dumper.add_representer(tuple, _represent_list)


def _to_plain(value):
    if dataclasses.is_dataclass(value):
        return {f.name: _to_plain(getattr(value, f.name)) for f in dataclasses.fields(value)}
    if isinstance(value, dict):
        return {str(k): _to_plain(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_to_plain(v) for v in value]
    return value


def _relativize_model_paths(task: dict) -> None:
    paths = task["model_path"]
    is_list = isinstance(paths, list)
    resolved = []
    for path in paths if is_list else [paths]:
        if not path or not Path(path).is_absolute():
            resolved.append(path)
            continue
        path_obj = Path(path).resolve()
        try:
            path_obj.relative_to(REPO_ROOT)
        except ValueError as exc:
            raise ValueError(f"Model path {path} is outside the repository; cannot export it portably.") from exc
        resolved.append(os.path.relpath(path_obj, PRESET_DIR))
    task["model_path"] = resolved if is_list else resolved[0]


def _preset_document(config) -> dict:
    document = _to_plain(config)
    _relativize_model_paths(document["task"])
    if document.get("secondary") is not None:
        _relativize_model_paths(document["secondary"]["task"])
    return document


def render_preset(name: str) -> str:
    from holosoma_inference.config.config_values.inference import INFERENCE_REGISTRY

    config = INFERENCE_REGISTRY.get(name)
    if config is None:
        raise KeyError(f"Unknown preset {name!r}. Available: {list(INFERENCE_REGISTRY.keys())}")
    body = yaml.dump(_preset_document(config), Dumper=_Dumper, sort_keys=False, width=120)
    return HEADER.format(name=name) + body


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="Exit non-zero if a preset file is stale.")
    args = parser.parse_args(argv)

    PRESET_DIR.mkdir(parents=True, exist_ok=True)
    stale = []
    for name in EXPORTED_PRESETS:
        path = PRESET_DIR / f"{name}.yaml"
        rendered = render_preset(name)
        current = path.read_text() if path.exists() else ""
        if current == rendered:
            continue
        if args.check:
            stale.append(name)
            sys.stdout.writelines(
                difflib.unified_diff(
                    current.splitlines(keepends=True),
                    rendered.splitlines(keepends=True),
                    fromfile=str(path),
                    tofile=f"{name} (from Python registry)",
                )
            )
        else:
            path.write_text(rendered)
            print(f"wrote {path}")

    if stale:
        print(f"\nStale C++ presets: {stale}. Run: python {Path(__file__).resolve().relative_to(REPO_ROOT)}")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
